## Basics

In [1]:
# enumerate

for value in range(5):
    print(value)

for idx, value in enumerate(range(5)):
    print(idx, value)

animals = ['cat', 'dog', 'horse']

for idx, value in enumerate(animals):
    print(idx, value)


0
1
2
3
4
0 0
1 1
2 2
3 3
4 4
0 cat
1 dog
2 horse


In [5]:
# fibonacci num
# f(n) = f(n-1) + f(n-2)

def fib(n):
    a, b = 0, 1

    while a < n:
        print(a)
        a, b, = b, a+b

fib(100)

0
1
1
2
3
5
8
13
21
34
55
89


### Python Object

In [1]:
a = 10
b = 10
print(id(a), id(b))
print(a == b, a is b)  # True, a and b point to the same object
print(type(a), type(b))
print()
print(bin(a))
print(a.bit_length())


a = a + 1
print(id(a), id(b))
print(a == b, a is b)  # False, a points to different object
print()

c = 11
print(id(a), id(c))
print(a == c, a is c)
print()

a += 100000000000000000000000000000000000000000000000000000000000000
print(a)
print(type(a))

4309901848 4309901848
True True
<class 'int'> <class 'int'>

0b1010
4
4309901880 4309901848
False False

4309901880 4309901880
True True

100000000000000000000000000000000000000000000000000000000000011
<class 'int'>


## Functions

In [11]:
def show_name(name, age):
    print(type(name))
    print("The name of the person is: " + name)
    print("The age of the person is {}".format(age))

show_name("Kevin", 10)  # Positaional Arguments - the order does matter
show_name(age=10, name="Tom")  # Keyword Arguments - the order does not matter

<class 'str'>
The name of the person is: Kevin
The age of the person is 10
<class 'str'>
The name of the person is: Tom
The age of the person is 10


In [6]:
# *args: variable positional arguments
def show_names(*names):
    print(type(names))
    for idx, name in enumerate(names):
        print(idx, name, type(name))

show_names("Kevin", "Adam", "Joe")
show_names("Kevin", 10)

<class 'tuple'>
0 Kevin <class 'str'>
1 Adam <class 'str'>
2 Joe <class 'str'>
<class 'tuple'>
0 Kevin <class 'str'>
1 10 <class 'int'>


In [10]:
# **kargs: an arbitrary number of keyword arguments
def show_names_(**params):
    # so it is a  dictionary with key and value pairs
    for keyword, argument in params.items():
        print(keyword, type(keyword), argument, type(argument))

show_names_(fname="Kevin", lname="Joe", age=20, gender="male")

fname <class 'str'> Kevin <class 'str'>
lname <class 'str'> Joe <class 'str'>
age <class 'str'> 20 <class 'int'>
gender <class 'str'> male <class 'str'>


In [14]:
# return
def mul(num1, num2):
    return num1 * num2

# return multiple values
def op(x):
    if x % 2 ==0:
        return True, 1, 'this is a even number.'
    return False, 0

print(mul(2, 3))
print(op(1))
print(op(2))

6
(False, 0)
(True, 1, 'this is a even number.')


In [17]:
# yield : it produces a sequence of values (objects). It can resume execution!

def producer():
    for num in range(10):
        if num % 2 == 0:
            return num

print(producer())

def producer_yield():
    for num in range(10):
        if num % 2 == 0:
            yield num

for num in producer_yield():
    print(num)


0
0
2
4
6
8


## Data Structure

In [1]:
# list comprehension: allows us to create a new list based on existing values of another list

numbers = [1, -5, 0, 10, 100, 67, 55, 20, 34]

new_list = []

for num in numbers:
    if num % 2 == 0:
        new_list.append(num)
print(new_list)

new_list_from_listcomp = [num for num in numbers if num % 2 == 0]
print(new_list_from_listcomp)

[0, 10, 100, 20, 34]
[0, 10, 100, 20, 34]


#### Mutability

- mutable objects allow modification after creation
  - lists, sets, dicts, and custom objects
- immutable objects do not allow modification after creation
  - int, float, boolean and tuple
- the memory location of mutable objects do not change when some of the value change - this is not true with immutable objects

In [3]:
# immutable objects - numbers, float, booleans, tuples
x = 5
print(id(x))

x = x + 1
print(id(x))  # x's address is changed.

# mutable objects
my_list = [1, 2, 3, 4]
print(id(my_list), id(my_list[0]))

my_list[0] = 10
print(id(my_list), id(my_list[0]))  # my_list address is not changed.

1928023730608
1928023730640
1928126359360 1928023730480
1928126359360 1928023730768


#### Sorting

In [9]:
nums = [10, -5, 0, 4, 8, -9, 34, 100]

# sorted function always return a list
result = sorted(nums)  
print(result)

result_reverse = sorted(nums, reverse=True)
print(result_reverse)

names = ['Adam', 'Kevin', 'Ana', 'Joe', 'Daniel', 'Michael']
sorted_names = sorted(names)
print(sorted_names)

# sorted fuunction has the KEY parameter - we can define the logic behind sorting
texts = ['This', 'This is a ', 'T', 'This is the longest string']
sorted(texts, key=len)

# sort dict
people = {'Adam Smith': 34, 'Albert Camus': 56, 'Kurt Godel': 45, 'Jean-Paul Sartre': 31}
sorted_people = sorted(people.items(), key=lambda x: x[0])  # item() returns the key values
print(sorted_people)
print(sorted_people[0])

[-9, -5, 0, 4, 8, 10, 34, 100]
[100, 34, 10, 8, 4, 0, -5, -9]
['Adam', 'Ana', 'Daniel', 'Joe', 'Kevin', 'Michael']
[('Adam Smith', 34), ('Albert Camus', 56), ('Jean-Paul Sartre', 31), ('Kurt Godel', 45)]
('Adam Smith', 34)


## Object Oriented Programming

In [14]:
class Person:
    name = 'Kevin'

    def show_name(self):
        print('My name is ' + self.name)

p = Person()
print(p.name)
p.show_name()

Kevin
My name is Kevin


In [18]:
# Using init
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def show_name(self):
        print(f'My name is {self.name} and my age is {self.age}')

p = Person('Kevin', 25)
q = Person(age=20, name='David')  # Use keyword argument
print(p.name)
p.show_name()

q.show_name()

Kevin
My name is Kevin and my age is 25
My name is David and my age is 20


In [22]:
# Class Variable vs. Instance Variable

class Person:
    # class variable
    gender = 'male'
    person_list = []

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def show_name(self):
        print(f'My name is {self.name} and my age is {self.age}')
    
    def add_value(self, value):
        self.person_list.append(value)

p = Person('Kevin', 25)
q = Person(age=20, name='David')  # Use keyword argument
print(p.name)
p.show_name()
q.show_name()
print(p.gender, q.gender)

p.add_value('person1')
q.add_value('person2')
print(p.person_list)
print(q.person_list)

Kevin
My name is Kevin and my age is 25
My name is David and my age is 20
male male
['person1', 'person2']
['person1', 'person2']


In [25]:
# super()

class User:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def show_user(self):
        print(f'The user is {self.name} and the age is {self.age}')
    
    def show_info(self):
        print('This is from User class.')

class FacebookUser(User):
    # super keyword is going to call the parent class
    def __init__(self, name, age):
        super().__init__(name, age)
    
    def show_info(self):
        print('This is from FacebookUser class.')

facebook_user = FacebookUser('Adam Smith', 35)
facebook_user.show_user()
facebook_user.show_info()


The user is Adam Smith and the age is 35
This is from FacebookUser class.


In [26]:
# Abstraction and Polymorphism

class SortingAlgorithm:
    def sort(self):
        pass

class InsertionSort(SortingAlgorithm):
    def sort(self):
        print('InsertionSort is running...')

class SelectionSort(SortingAlgorithm):
    def sort(self):
        print('SelectionSort is running...')

class QuickSort(SortingAlgorithm):
    def sort(self):
        print('QuickSort is running...')

sort_algo = [InsertionSort(), SelectionSort(), QuickSort()]

sort_algo[0].sort()
sort_algo[1].sort()
sort_algo[2].sort()

InsertionSort is running...
SelectionSort is running...
QuickSort is running...


## Numpy

In [38]:
import numpy as np

# Reshape
# the shape is the number of items in each dimension
def print_shape(nums):
    print(nums)
    print(nums.shape)
    print()

nums = np.array([1, 2, 3, 4, 5, 6])
print_shape(nums)

nums = nums.reshape(2, 3)
print_shape(nums)

nums = nums.reshape(3, 2)
print_shape(nums)

nums = nums.reshape(6, 1)
print_shape(nums)

# We can use -1 : unkonwn dimension
nums = nums.reshape(6, -1)  # same as reshape(6, 1)
print_shape(nums)

nums = nums.reshape(-1, 3)
print_shape(nums)

nums = nums.reshape(1, -1)
print_shape(nums)

nums = nums.reshape(-1, 1)
print_shape(nums)

[1 2 3 4 5 6]
(6,)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2 3 4 5 6]]
(1, 6)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)



In [43]:
# stacking and merging arrays

import numpy as np

a = np.array([[1, 2, 3], [7, 8,9]])
b = np.array([[5, 6, 7], [10, 11, 12]])
print_shape(a)

# Vertical Stack
result = np.vstack((a, b))
print_shape(result)

# Horizontal Stack
result = np.hstack((a, b))
print_shape(result)

# Stack
result = np.stack((a, b), axis=0)
print_shape(result)

result = np.stack((a, b), axis=1)
print_shape(result)

[[1 2 3]
 [7 8 9]]
(2, 3)

[[ 1  2  3]
 [ 7  8  9]
 [ 5  6  7]
 [10 11 12]]
(4, 3)

[[ 1  2  3  5  6  7]
 [ 7  8  9 10 11 12]]
(2, 6)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 5  6  7]
  [10 11 12]]]
(2, 2, 3)

[[[ 1  2  3]
  [ 5  6  7]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)



In [47]:
# Filtering

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
boolean_array = [True, True, False, False, True, False, True, False]

result = a[boolean_array]
print(result)

result = a < 4
print(a[result])

[1 2 5 7]
[1 2 3]


In [48]:
import time
import numpy as np
 
# manipulating a 10 million items
n = 10000000
 
 
def numpy_add():
    # time in seconds
    now = time.time()
    # generating a 10 million items
    x = np.arange(n)
    # generating a 10 million items
    y = np.arange(n)
    result = x + y
    return time.time() - now
 
 
def python_add():
    # time in seconds
    now = time.time()
    # generating a 10 million items
    x = range(n)
    # generating a 10 million items
    y = range(n)
    result = [x[i] + y[i] for i in range(len(x))]
    return time.time() - now
 
 
time_python = python_add()
time_numpy = numpy_add()
print('Python time: ' + str(time_python) + 's')
print('NumPy time: ' + str(time_numpy) + 's')
print("Numpy is " + str(time_python/time_numpy) + "x faster!")

Python time: 1.0117840766906738s
NumPy time: 0.02307605743408203s
Numpy is 43.84562135801959x faster!
