# View, Tranpose, and Reshape


In [2]:
import torch

t_4x3x2 = torch.tensor([[[0, 1], [2, 3], [4, 5]],
                  [[6, 7], [8, 9], [10, 11]],
                  [[12, 13], [14, 15], [16, 17]],
                  [[18, 19], [20, 21], [22, 23]]])
t_4x3x2

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])

In [4]:
t_view_4x2x3 = t_4x3x2.view(4, 2, 3)
t_view_4x2x3

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])

In [5]:
t_4x3x2.is_contiguous(), t_view_4x2x3.is_contiguous()

(True, True)

In [6]:
t_4x3x2.flatten() == t_view_4x2x3.flatten()

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True])

In [7]:
t_4x3x2.storage().data_ptr() == t_view_4x2x3.storage().data_ptr()

True

In [9]:
# Transpose
t_trasnposed_4x2x3 = t_4x3x2.transpose(2, 1)
t_trasnposed_4x2x3

tensor([[[ 0,  2,  4],
         [ 1,  3,  5]],

        [[ 6,  8, 10],
         [ 7,  9, 11]],

        [[12, 14, 16],
         [13, 15, 17]],

        [[18, 20, 22],
         [19, 21, 23]]])

In [10]:
t_trasnposed_4x2x3.is_contiguous()

False

In [11]:
t_trasnposed_4x2x3.flatten()

tensor([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11, 12, 14, 16, 13, 15, 17,
        18, 20, 22, 19, 21, 23])

In [12]:
# Contiguous
t_trasnposed_4x2x3.contiguous() == t_trasnposed_4x2x3

tensor([[[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]]])

In [14]:
t_trasnposed_4x2x3.contiguous().storage().data_ptr() == t_trasnposed_4x2x3.storage().data_ptr()

False

## Reshape == contiguous().view()

In [15]:
t_trasnposed_4x2x3.view(4, 3, 2)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [16]:
t_trasnposed_4x2x3.contiguous().view(4, 3, 2)

tensor([[[ 0,  2],
         [ 4,  1],
         [ 3,  5]],

        [[ 6,  8],
         [10,  7],
         [ 9, 11]],

        [[12, 14],
         [16, 13],
         [15, 17]],

        [[18, 20],
         [22, 19],
         [21, 23]]])

In [17]:
t_trasnposed_4x2x3.reshape(4, 3, 2)

tensor([[[ 0,  2],
         [ 4,  1],
         [ 3,  5]],

        [[ 6,  8],
         [10,  7],
         [ 9, 11]],

        [[12, 14],
         [16, 13],
         [15, 17]],

        [[18, 20],
         [22, 19],
         [21, 23]]])

In [18]:
t_trasnposed_4x2x3.reshape(4, 3, 2).is_contiguous()

True

In [31]:
# Narrow, keep contiguous, on the outmost dimension only
t_narrowed = t_4x3x2.narrow(0, 1, 1)  # dim, start, length
t_4x3x2, t_narrowed, t_narrowed.is_contiguous()

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]],
 
         [[12, 13],
          [14, 15],
          [16, 17]],
 
         [[18, 19],
          [20, 21],
          [22, 23]]]),
 tensor([[[ 6,  7],
          [ 8,  9],
          [10, 11]]]),
 True)

In [36]:
# Narrow, broken contiguous
t_narrowed = t_4x3x2.narrow(1, 1, 1)  # dim, start, length
t_4x3x2, t_narrowed, t_narrowed.is_contiguous()

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]) tensor([[[ 2,  3]],

        [[ 8,  9]],

        [[14, 15]],

        [[20, 21]]]) False


In [35]:
t_narrowed = t_4x3x2.narrow(2, 1, 1)  # dim, start, length
t_4x3x2, t_narrowed, t_narrowed.is_contiguous()

(tensor([[[ 0,  1],
          [ 2,  3],
          [ 4,  5]],
 
         [[ 6,  7],
          [ 8,  9],
          [10, 11]],
 
         [[12, 13],
          [14, 15],
          [16, 17]],
 
         [[18, 19],
          [20, 21],
          [22, 23]]]),
 tensor([[[ 1],
          [ 3],
          [ 5]],
 
         [[ 7],
          [ 9],
          [11]],
 
         [[13],
          [15],
          [17]],
 
         [[19],
          [21],
          [23]]]),
 False)

In [56]:
# Expand
t = torch.tensor([[1], [2], [3]])
print(t.size())
t_expanded = t.expand(3, 4)  # does not allocate new memory, just change the view
print(t_expanded, t_expanded.size(), t_expanded.is_contiguous())

t_con = t_expanded.reshape(3, 4)  # Not contiguous
print(t_con, t_con.size(), t_con.is_contiguous())

t_con = t_expanded.reshape(4, 3)
print(t_con, t_con.size(), t_con.is_contiguous())

torch.Size([3, 1])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4]) False
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4]) False
tensor([[1, 1, 1],
        [1, 2, 2],
        [2, 2, 3],
        [3, 3, 3]]) torch.Size([4, 3]) True
